### ISSUE TITLE
How can I listen for changes of selection?

### ISSUE THREAD

**Issue by umutzd** [fontIconPicker/fontIconPicker#15]
I need to listen for changes in selection so that I can send this new knowledge to the server. But I can't figure out how, since there is no callback method documented about any event.

**Comment by swashata** [comment]
Hello,

This works like any jQuery `change` event.

```js
jQuery(document).ready(function($) {
    // First icon picker with fontawesome
    $('#e10_element_1').fontIconPicker({
        theme: 'fip-darkgrey',
        source: fnt_icons_categorized
    }).on('change', function() {
        var selectedIcon = $(this).val();
        // do something with selectedIcon
    });
});
```

Check the example `Trigger event on icon change` here https://fonticonpicker.github.io/
