### ISSUE TITLE
Selector popup menu shows one second then close

### ISSUE THREAD

**Issue by rerraw** [fontIconPicker/fontIconPicker#6]
Today I integrate the fonticonpicker plugin to entire my WordPress nave menu. everything works perfectly but when I click on selector button the selector popup menu open for one second then close.

**Comment by swashata** [comment]
I remember having same problem. It was some sort of event trigger. I can't recall how I managed to work it out, but it definitely has something to do with the navmenu javascript of WP. Maybe you can set `autoClose` to `false` for fontIconPicker.

**Comment by rerraw** [comment]
Thank you for a reply to me 
I changed the input id then worked with me I used the `id="edit-menu-item-faicons-color-<?php echo $item_id; ?>"` the popup menu not work with this id
then i changed the id to simple text worked with me without any problem

**Comment by swashata** [comment]
Great.
